/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-04-29 02:32:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.professors;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ex0429.*;
import java.util.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>교수목록</title>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t.title{text-align: center; background: gray; color: white;}\r\n");
      out.write("\t\t.row:hover{background: gray; color: white; cursor: pointer;}\r\n");
      out.write("\t\t#slist,#clist{display: none;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>[교수목록]</h1>\r\n");
      out.write("\t<table id=\"tbl\" border=1 width=700>\r\n");
      out.write("\t\t<tr class=title>\r\n");
      out.write("\t\t\t<td>교수번호</td>\r\n");
      out.write("\t\t\t<td>교수이름</td>\r\n");
      out.write("\t\t\t<td>교수학과</td>\r\n");
      out.write("\t\t\t<td>생년월일</td>\r\n");
      out.write("\t\t\t<td>교수직급</td>\r\n");
      out.write("\t\t\t<td>교수급여</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			PDAO dao=new PDAO();
			ArrayList<PVO> list=dao.list();
			for(PVO vo:list){
				out.println("<tr class=row>");
				out.println("<td class=pcode>"+vo.getPcode()+"</td>");
				out.println("<td class=pname>"+vo.getPname()+"</td>");
				out.println("<td>"+vo.getDept()+"</td>");
				out.println("<td>"+vo.getHiredate()+"</td>");
				out.println("<td>"+vo.getTitle()+"</td>");
				out.println("<td>"+vo.getSalary()+"</td>");
				out.println("</td>");
			}
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div id=\"slist\">\r\n");
      out.write("\t\t<h1>[학생목록]</h1>\r\n");
      out.write("\t\t<div>담당교수:<span class=\"pname\"></span></div>\r\n");
      out.write("\t\t<table id=\"stbl\" border=1 width=700></table>\r\n");
      out.write("\t    <script id=\"temp1\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t\t<tr class=title>\r\n");
      out.write("\t\t\t\t<td>학생번호</td>\r\n");
      out.write("\t\t\t\t<td>학생이름</td>\r\n");
      out.write("\t\t\t\t<td>학생학과</td>\r\n");
      out.write("\t\t\t\t<td>학년</td>\r\n");
      out.write("\t\t\t\t<td>생년월일</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("    \t\t{{#each slist}}\r\n");
      out.write("         \t<tr>\r\n");
      out.write("            \t<td>{{scode}}</td>\r\n");
      out.write("           \t\t<td>{{sname}}</td>\r\n");
      out.write("           \t\t<td>{{dept}}</td>\r\n");
      out.write("           \t\t<td>{{year}}</td>\r\n");
      out.write("\t\t\t\t<td>{{birthday}}</td>\r\n");
      out.write("         \t</tr>\r\n");
      out.write("        \t{{/each}}\r\n");
      out.write("      \t</script>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t<div id=\"clist\">\r\n");
      out.write("\t\t<h1>[강좌목록]</h1>\r\n");
      out.write("\t\t<div>담당교수:<span class=\"pname\"></span></div>\r\n");
      out.write("\t\t<table id=\"ctbl\" border=1 width=700></table>\r\n");
      out.write("\t    <script id=\"temp2\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t\t<tr class=title>\r\n");
      out.write("\t\t\t\t<td>강좌번호</td>\r\n");
      out.write("\t\t\t\t<td>강좌이름</td>\r\n");
      out.write("\t\t\t\t<td>강의시간수</td>\r\n");
      out.write("\t\t\t\t<td>강의실</td>\r\n");
      out.write("\t\t\t\t<td>수강생인원</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("    \t\t{{#each clist}}\r\n");
      out.write("         \t<tr>\r\n");
      out.write("            \t<td>{{lcode}}</td>\r\n");
      out.write("           \t\t<td>{{lname}}</td>\r\n");
      out.write("           \t\t<td>{{hours}}</td>\r\n");
      out.write("           \t\t<td>{{room}}</td>\r\n");
      out.write("\t\t\t\t<td>{{persons}}</td>\r\n");
      out.write("         \t</tr>\r\n");
      out.write("        \t{{/each}}\r\n");
      out.write("      \t</script>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar pcode;\r\n");
      out.write("\t$(\"#tbl\").on(\"click\",\".row\",function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tpcode=$(this).find(\".pcode\").html();\r\n");
      out.write("\t\tvar pname=$(this).find(\".pname\").html();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#slist\").show();\r\n");
      out.write("\t\t$(\"#clist\").show();\r\n");
      out.write("\t\t$(\"#slist .pname\").html(pname);\r\n");
      out.write("\t\t$(\"#clist .pname\").html(pname);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tgetList();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getList(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t    $.ajax({\r\n");
      out.write("\t        type:\"get\",\r\n");
      out.write("\t        url:\"json.jsp\",\r\n");
      out.write("\t        dataType:\"json\",\r\n");
      out.write("\t        data:{\"pcode\":pcode},\r\n");
      out.write("\t        success:function(data){\r\n");
      out.write("\t           var temp=Handlebars.compile($(\"#temp1\").html());\r\n");
      out.write("\t           $(\"#stbl\").html(temp(data));\r\n");
      out.write("\t           \r\n");
      out.write("\t           var temp=Handlebars.compile($(\"#temp2\").html());\r\n");
      out.write("\t           $(\"#ctbl\").html(temp(data));\r\n");
      out.write("\t        }\r\n");
      out.write("\t   \t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
